name: Dependency Management

on: [push]

jobs:
  nodejs-tests:
    name: NodeJS Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - run: cd BidWars-NodeJS/ && npm ci
      - run: cd BidWars-NodeJS/ && npm audit

  java-tests:
    name: Java Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - run: chmod +x mvnw
      - run: cd BidWars-Java && ./mvnw clean install
